"""Direct `(f, g)` ideal-membership periods for Algorithm SM.1."""

from math import gcd

from sage.all import FreeModule, lcm

from isomorphism.algebra.singular_backend import (
    laurent_to_polynomial,
    reduce_by_standard_basis,
    standard_basis,
)
from isomorphism.periods.search import PeriodData, SuperlatticeData
from isomorphism.rings import P, PRESENTATION, module_element, x, y


class LaurentIdealMembership:
    """Normal-form membership tester for a Laurent ideal.

    The tester lifts Laurent generators to the ordinary polynomial ring used by
    Singular and augments them with inverse-variable relations. Membership is
    then tested by reducing a lifted target to normal form.
    """

    def __init__(self, generators):
        """Build one lifted standard basis for repeated membership tests.

        Args:
            generators: Iterable of Laurent polynomial ideal generators.
        """
        module = FreeModule(P, 1)
        lifted = [
            module_element(module, [laurent_to_polynomial(generator)]) for generator in generators
        ]
        inverse = [
            module_element(module, [relation]) for relation in PRESENTATION.inverse_relations()
        ]
        # The inverse relations make ordinary polynomial reduction represent
        # Laurent ideal membership.
        self.module = module
        self.standard_basis = standard_basis([*lifted, *inverse])

    def contains(self, poly):
        """Return whether ``poly`` lies in the represented Laurent ideal.

        Args:
            poly: Laurent polynomial to test.

        Returns:
            True when the lifted normal form is zero.
        """
        lifted = module_element(self.module, [laurent_to_polynomial(poly)])
        return reduce_by_standard_basis(lifted, self.standard_basis).is_zero()


def _find_axis_period(ideal, variable, max_period, axis):
    """Find the smallest positive period along one lattice axis.

    Args:
        ideal: ``LaurentIdealMembership`` tester.
        variable: Laurent variable ``x`` or ``y``.
        max_period: Inclusive search bound.
        axis: Axis name used in error messages.

    Returns:
        Smallest positive period along the axis.

    Raises:
        ValueError: If no bounded period is found.
    """
    if max_period is None:
        raise ValueError("max_period is required for bounded ideal period search.")
    for period in range(1, max_period + 1):
        if ideal.contains(variable**period + 1):
            return period
    raise ValueError(f"No {axis} ideal period was found within max_period.")


def _superlattice_from_ideal(ideal, max_period):
    """Find Algorithm SM.1 oblique superlattice data for one ideal.

    Args:
        ideal: ``LaurentIdealMembership`` tester.
        max_period: Inclusive search bound.

    Returns:
        ``SuperlatticeData`` with oblique basis parameters.

    Raises:
        ValueError: If no bounded superlattice is found.
    """
    alpha = _find_axis_period(ideal, x, max_period, "x")
    for delta in range(1, max_period + 1):
        if ideal.contains(y**delta + 1):
            return SuperlatticeData(
                alpha,
                0,
                delta,
                {"path": "ideal_membership", "max_period": max_period},
            )
        for gamma in range(1, alpha):
            # Search the second oblique generator x^gamma y^delta.
            if ideal.contains(x**gamma * y**delta + 1):
                return SuperlatticeData(
                    alpha,
                    gamma,
                    delta,
                    {"path": "ideal_membership", "max_period": max_period},
                )
    raise ValueError("No ideal superlattice basis was found within max_period.")


def _square_period_from_superlattice(superlattice):
    """Return the smallest square period implied by oblique lattice data.

    Args:
        superlattice: Oblique period data.

    Returns:
        Smallest square period containing the oblique lattice.
    """
    # To find (L, 0) and (0, L) which are both generated by (alpha, 0) and (gamma, delta)
    # We must find some k * alpha = beta * gamma, the smallest positive beta is alpha // gcd(alpha, gamma) 
    # and the corresponding k is gamma // gcd(alpha, gamma).
    y_period = superlattice.delta * superlattice.alpha // gcd(
        superlattice.alpha,
        superlattice.gamma,
    )
    return int(lcm(superlattice.alpha, y_period))


def _ceil_div(numerator, denominator):
    """Return ``ceil(numerator / denominator)`` for a positive denominator.

    Args:
        numerator: Integer numerator.
        denominator: Positive integer denominator.

    Returns:
        Exact integer ceiling.
    """
    return -((-numerator) // denominator)


def _vectors_from_superlattice(superlattice, square_period):
    """Enumerate period-square lattice vectors without ideal membership calls.

    Args:
        superlattice: Oblique period data.
        square_period: Square period bound.

    Returns:
        Sorted tuple of nonzero period vectors inside the square.
    """
    vectors = set()
    for beta in range(square_period // superlattice.delta + 1):
        py = beta * superlattice.delta
        base_x = beta * superlattice.gamma
        # Solve px = alpha*k + gamma*beta with px constrained to the square.
        min_alpha_multiple = _ceil_div(-base_x, superlattice.alpha)
        max_alpha_multiple = (square_period - base_x) // superlattice.alpha
        for alpha_multiple in range(min_alpha_multiple, max_alpha_multiple + 1):
            px = alpha_multiple * superlattice.alpha + base_x
            if (px, py) != (0, 0):
                vectors.add((px, py))
    return tuple(sorted(vectors))


def superlattice_from_generators(f, g, *, max_period):
    """Return Algorithm SM.1 oblique superlattice data from ideal generators.

    Args:
        f: First Laurent ideal generator.
        g: Second Laurent ideal generator.
        max_period: Inclusive bounded period search.

    Returns:
        ``SuperlatticeData`` for the Laurent ideal ``(f, g)``.
    """
    ideal = LaurentIdealMembership([f, g])
    return _superlattice_from_ideal(ideal, max_period)


def periods_from_generators(f, g, *, max_period):
    """Compute period data directly from the Laurent ideal ``(f, g)``.

    Args:
        f: First Laurent ideal generator.
        g: Second Laurent ideal generator.
        max_period: Inclusive bounded period search.

    Returns:
        ``PeriodData`` containing all period vectors inside the implied square.

    Raises:
        ValueError: If the combined square period exceeds ``max_period``.
    """
    ideal = LaurentIdealMembership([f, g])
    superlattice = _superlattice_from_ideal(ideal, max_period)
    period = _square_period_from_superlattice(superlattice)
    if period > max_period:
        raise ValueError("Combined ideal period exceeds max_period.")
    vectors = _vectors_from_superlattice(superlattice, period)
    return PeriodData(
        vectors,
        period,
        {
            "path": "ideal_membership",
            "superlattice": (
                superlattice.alpha,
                superlattice.gamma,
                superlattice.delta,
            ),
        },
    )
