"""Finite period-vector search helpers for Algorithm SM.1."""

from dataclasses import dataclass, field

from sage.all import identity_matrix, lcm


@dataclass(frozen=True)
class PeriodData:
    """Period vectors plus the square bound used to enumerate them.

    Attributes:
        vectors: Nonzero lattice vectors accepted as periods.
        square_period: Square period used to enumerate candidate vectors.
        diagnostics: Optional algorithm path and debugging data.
    """

    vectors: tuple
    square_period: int
    diagnostics: dict = field(default_factory=dict)


@dataclass(frozen=True)
class SuperlatticeData:
    """Triangular superlattice parameters from Algorithm SM.1.

    Attributes:
        alpha: Positive x-axis period.
        gamma: Horizontal component of the second triangular generator.
        delta: Positive y component of the second triangular generator.
        diagnostics: Optional algorithm path and debugging data.
    """

    alpha: int
    gamma: int
    delta: int
    diagnostics: dict = field(default_factory=dict)

    @property
    def cell(self):
        """Return the oblique cell generated by the triangular parameters.

        Returns:
            Pair ``((alpha, 0), (gamma, delta))``.
        """
        return ((self.alpha, 0), (self.gamma, self.delta))


def enumerate_period_vectors(period, membership):
    """Enumerate nonzero vectors in the period square accepted by membership.

    Args:
        period: Square search bound.
        membership: Callable ``membership(px, py) -> bool``.

    Returns:
        Tuple of accepted nonzero vectors in ``[0, period]^2``.
    """
    vectors = []
    for px in range(period + 1):
        for py in range(period + 1):
            if (px, py) != (0, 0) and membership(px, py):
                vectors.append((px, py))
    return tuple(vectors)


def choose_smallest_oblique_cell(period_vectors):
    """Choose independent vectors with minimum area and low coordinate degree.

    Args:
        period_vectors: Iterable of candidate period vectors.

    Returns:
        Pair ``(u, v)`` of independent vectors.

    Raises:
        ValueError: If no independent pair exists.
    """
    best = None
    vectors = list(period_vectors)
    for index, u in enumerate(vectors):
        for v in vectors[index + 1 :]:
            area = abs(u[0] * v[1] - u[1] * v[0])
            if area:
                # Area is primary.  The coordinate tie-breakers keep the
                # selected cell compact and stable for equivalent candidates.
                max_coordinate = max(abs(u[0]), abs(u[1]), abs(v[0]), abs(v[1]))
                l1_coordinate = abs(u[0]) + abs(u[1]) + abs(v[0]) + abs(v[1])
                score = (area, max_coordinate, l1_coordinate, u, v)
                if best is None or score < best[0]:
                    best = (score, u, v)
    if best is None:
        raise ValueError("Period vectors do not contain an independent cell.")
    return best[1], best[2]


def _matrix_order(action, *, max_period, axis):
    """Find a bounded finite order for one translation matrix.

    Args:
        action: Square translation action matrix.
        max_period: Inclusive search bound.
        axis: Axis name used in error messages.

    Returns:
        Smallest positive period within ``max_period``.

    Raises:
        ValueError: If no bounded period is found.
    """
    identity = identity_matrix(action.base_ring(), action.nrows())
    for period in range(1, max_period + 1):
        if action**period == identity:
            return period
    raise ValueError(f"No {axis} action period was found within max_period.")


def periods_from_translation_action(tx, ty, *, max_period):
    """Return period vectors of finite commuting translation matrices.

    Args:
        tx: Matrix representing multiplication by x on a quotient basis.
        ty: Matrix representing multiplication by y on the same quotient basis.
        max_period: Inclusive bounded search period.

    Returns:
        ``PeriodData`` for the finite action.

    Raises:
        ValueError: If the matrices are incompatible or no bounded period is
            found.
    """
    if tx.nrows() != tx.ncols() or ty.nrows() != ty.ncols() or tx.nrows() != ty.nrows():
        raise ValueError("Translation action matrices must be square with matching size.")
    if max_period is None:
        raise ValueError("max_period is required for bounded translation-action search.")
    # Independent axis orders bound the full commuting action by their lcm.
    period = lcm(
        _matrix_order(tx, max_period=max_period, axis="x"),
        _matrix_order(ty, max_period=max_period, axis="y"),
    )
    if period > max_period:
        raise ValueError("Combined action period exceeds max_period.")
    identity = identity_matrix(tx.base_ring(), tx.nrows())
    # A vector is a period exactly when the combined translation action is the
    # identity on the quotient.
    vectors = enumerate_period_vectors(period, lambda px, py: tx**px * ty**py == identity)
    return PeriodData(vectors, period, {"path": "translation_action"})


def superlattice_from_translation_action(tx, ty, *, max_period):
    """Return Algorithm SM.1 parameters for finite translation actions.

    Args:
        tx: Matrix representing multiplication by x on a quotient basis.
        ty: Matrix representing multiplication by y on the same quotient basis.
        max_period: Inclusive bounded search period.

    Returns:
        ``SuperlatticeData`` with triangular period basis.

    Raises:
        ValueError: If the matrices are incompatible or no bounded
            superlattice is found.
    """
    if tx.nrows() != tx.ncols() or ty.nrows() != ty.ncols() or tx.nrows() != ty.nrows():
        raise ValueError("Translation action matrices must be square with matching size.")
    if max_period is None:
        raise ValueError("max_period is required for bounded translation-action search.")
    identity = identity_matrix(tx.base_ring(), tx.nrows())
    alpha = _matrix_order(tx, max_period=max_period, axis="x")
    x_powers = {0: identity}
    # Cache x^gamma once; the outer loop changes only y^delta.
    for gamma in range(1, alpha):
        x_powers[gamma] = tx**gamma
    for delta in range(1, max_period + 1):
        y_delta = ty**delta
        if y_delta == identity:
            return SuperlatticeData(
                alpha,
                0,
                delta,
                {"path": "translation_action", "max_period": max_period},
            )
        for gamma in range(1, alpha):
            if x_powers[gamma] * y_delta == identity:
                return SuperlatticeData(
                    alpha,
                    gamma,
                    delta,
                    {"path": "translation_action", "max_period": max_period},
                )
    raise ValueError("No superlattice basis was found within max_period.")
