"""Verify the paper examples through period search and coarse-graining."""

import _bootstrap  # noqa: F401

from sage.all import GF, Matrix, identity_matrix

from decoupling import (
    R,
    coarse_grain_to_superlattice,
    compute_translation_representation,
    find_anyon_preserving_superlattice_from_generators,
    find_anyon_preserving_superlattice_from_translation_representation,
    oblique_cell,
    x,
    y,
)
from decoupling.css import check_commutation, split_css_blocks
from decoupling.paper_examples import COLOR_CODE_488, COLOR_CODE_666


def cell_index(u, v):
    """Return the index of the lattice generated by ``u`` and ``v``."""
    return abs(u[0] * v[1] - u[1] * v[0])


def minimum_period_index(period_vectors):
    """Return the minimum index of an independent period-vector pair."""
    indices = [
        cell_index(u, v)
        for index, u in enumerate(period_vectors)
        for v in period_vectors[index + 1 :]
        if cell_index(u, v)
    ]
    return min(indices)


def check_oblique_cell(basis):
    """Check exact point decomposition throughout several neighboring cells."""
    u, v = basis
    cell = oblique_cell(u, v)
    assert cell.area == cell_index(u, v)
    for point_x in range(-3, 4):
        for point_y in range(-3, 4):
            slot, cell_x, cell_y = cell.decompose(point_x, point_y)
            assert cell.compose(slot, cell_x, cell_y) == (point_x, point_y)


def check_reference_basis(periods, basis):
    """Check that a paper basis is period preserving and minimum index."""
    u, v = basis
    assert u in periods.period_vectors
    assert v in periods.period_vectors
    assert cell_index(u, v) == minimum_period_index(periods.period_vectors)
    check_oblique_cell(basis)


excitation_666 = COLOR_CODE_666.excitation_map()
translation_666 = compute_translation_representation(excitation_666[:1, :2])
expected_translation_666 = Matrix(GF(2), [[0, 1], [1, 1]])
assert translation_666.tx == expected_translation_666
assert translation_666.ty == expected_translation_666
assert translation_666.tx**3 == identity_matrix(GF(2), 2)
assert translation_666.tx != identity_matrix(GF(2), 2)
assert translation_666.tx**2 != identity_matrix(GF(2), 2)

f_666, g_666 = 1 + x + x * y, 1 + y + x * y
periods_666 = find_anyon_preserving_superlattice_from_generators(
    f_666,
    g_666,
    max_period=3,
)
assert periods_666.square_period == COLOR_CODE_666.reference_square_period

excitation_488 = COLOR_CODE_488.excitation_map()
translation_488 = compute_translation_representation(excitation_488[:2, :4])
expected_translation_488 = Matrix(GF(2), [[1, 0], [1, 1]])
assert translation_488.tx == expected_translation_488
assert translation_488.ty == expected_translation_488
assert translation_488.tx**2 == identity_matrix(GF(2), 2)
assert translation_488.tx != identity_matrix(GF(2), 2)

full_translation_488 = compute_translation_representation(excitation_488)
periods_488 = find_anyon_preserving_superlattice_from_translation_representation(
    full_translation_488.tx,
    full_translation_488.ty,
    max_period=2,
)
assert periods_488.square_period == COLOR_CODE_488.reference_square_period

check_reference_basis(periods_666, COLOR_CODE_666.superlattice_basis)
check_reference_basis(periods_488, COLOR_CODE_488.superlattice_basis)

# These matrices use the canonical half-open representatives selected by
# ``oblique_cell``.  The paper's displayed matrices use equivalent monomial
# row/column bases, so their entries need not agree before those basis changes.
canonical_h_x_666 = Matrix(
    R,
    [
        [1, y, x, 1, y, y],
        [1, 1, y, x**-1 * y, 1, y],
        [x**-1 * y, 1, 1, x**-1 * y, x**-1 * y, 1],
    ],
)
canonical_h_z_666 = Matrix(
    R,
    [
        [1, x * y**-1, x * y**-1, 1, 1, x * y**-1],
        [y**-1, 1, x * y**-1, y**-1, 1, 1],
        [y**-1, y**-1, 1, x**-1, y**-1, 1],
    ],
)
canonical_h_x_488 = Matrix(
    R,
    [
        [1, y, 1, y, 1, x, 1, x],
        [x**-1 * y, 1, x**-1 * y, 1, 1, 1, 1, 1],
        [y, 0, 0, y, y, 0, 0, x],
        [0, y, x**-1 * y, 0, 0, y, 1, 0],
    ],
)
canonical_h_z_488 = canonical_h_x_488

for case, excitation, expected_h_z, expected_h_x in (
    (
        COLOR_CODE_666,
        excitation_666,
        canonical_h_z_666,
        canonical_h_x_666,
    ),
    (
        COLOR_CODE_488,
        excitation_488,
        canonical_h_z_488,
        canonical_h_x_488,
    ),
):
    coarse = coarse_grain_to_superlattice(
        excitation,
        *case.superlattice_basis,
    )
    num_x_checks = coarse.nrows() // 2
    num_qubits = coarse.ncols() // 2
    actual_h_z, actual_h_x = split_css_blocks(
        coarse,
        num_x_checks,
        num_qubits,
    )
    assert actual_h_x == expected_h_x
    assert actual_h_z == expected_h_z
    assert num_qubits == case.reference_q
    assert check_commutation(excitation, excitation.ncols() // 2)
    assert check_commutation(coarse, num_qubits)

print("test_paper_periods_and_coarse_graining: ok")
